# Generated by Django 3.0.7 on 2020-07-28 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('place', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=65536)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.CharField(default='', max_length=200, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feed_Tag',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('feed_tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeedsApi.Feed')),
                ('tag_tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeedsApi.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='Feed_Like',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('feed_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeedsApi.Feed')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_Like',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('Comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeedsApi.Comment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments_Comment',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('some comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeedsApi.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='feed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeedsApi.Feed'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
